---
- hosts: webserver
  become: true
  vars:
    pacotes:
      - vim
      - tree
      - btop

  tasks:
    - name: Atualizar cache do APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar pacotes
      apt:
        name: "{{ pacotes }}"
        state: present